"""removed chatroom record messages column and user friend count column

Revision ID: 5b4d53bb6603
Revises: 6ef5d1a23117
Create Date: 2026-03-31 11:08:59.018282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b4d53bb6603"
down_revision: Union[str, Sequence[str], None] = "6ef5d1a23117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatroom", "record_messages")
    op.drop_column("user", "friend_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("friend_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "chatroom",
        sa.Column("record_messages", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
