"""user friendship link tables add on delete args

Revision ID: 6ef5d1a23117
Revises: eb332cbe8957
Create Date: 2026-03-14 16:41:14.268478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ef5d1a23117"
down_revision: Union[str, Sequence[str], None] = "eb332cbe8957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "userfriendship", "user", ["user_uid"], ["uid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "userfriendship", "user", ["friend_uid"], ["uid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userfriendship", type_="foreignkey")
    op.drop_constraint(None, "userfriendship", type_="foreignkey")
    # ### end Alembic commands ###
