"""initial

Revision ID: eb332cbe8957
Revises:
Create Date: 2026-03-11 17:56:40.157778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "eb332cbe8957"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_email",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blacklisted_email_sub"), "blacklisted_email", ["sub"], unique=True
    )
    op.create_table(
        "blacklisted_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.Uuid(), nullable=False),
        sa.Column("exp", sa.Float(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blacklisted_token_jti"), "blacklisted_token", ["jti"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column(
            "google_oauth2_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.Column("modified_at", sa.Float(), nullable=True),
        sa.Column("last_seen", sa.Float(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
        sa.Column("is_two_factor_authenticated", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_google_oauth2_id"), "user", ["google_oauth2_id"], unique=False
    )
    op.create_table(
        "chatroom",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("about", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "original_creator_username",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("members_count", sa.Integer(), nullable=True),
        sa.Column(
            "room_type",
            sa.Enum("private", "public", "personal", name="chatroomtype"),
            nullable=True,
        ),
        sa.Column("record_messages", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.Column("modified_at", sa.Float(), nullable=True),
        sa.Column("creator_uid", sa.Uuid(), nullable=True),
        sa.Column("creator_successor_uid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_successor_uid"], ["user.uid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["creator_uid"], ["user.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "userfriendship",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("friend_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["friend_uid"],
            ["user.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["user.uid"],
        ),
        sa.PrimaryKeyConstraint("user_uid", "friend_uid"),
    )
    op.create_table(
        "userfriendshiprequest",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("request_friend_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_friend_uid"],
            ["user.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["user.uid"],
        ),
        sa.PrimaryKeyConstraint("user_uid", "request_friend_uid"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.Column("sender_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sender_uid", sa.Uuid(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chatroom_uid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["chatroom_uid"], ["chatroom.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userchatroombannedlink",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("chatroom_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["chatroom_uid"], ["chatroom.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_uid"], ["user.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_uid", "chatroom_uid"),
    )
    op.create_table(
        "userchatroomlink",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("chatroom_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["chatroom_uid"], ["chatroom.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_uid"], ["user.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_uid", "chatroom_uid"),
    )
    op.create_table(
        "userchatroommoderatorslink",
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("chatroom_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["chatroom_uid"], ["chatroom.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_uid"], ["user.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_uid", "chatroom_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userchatroommoderatorslink")
    op.drop_table("userchatroomlink")
    op.drop_table("userchatroombannedlink")
    op.drop_table("message")
    op.drop_table("userfriendshiprequest")
    op.drop_table("userfriendship")
    op.drop_table("chatroom")
    op.drop_index(op.f("ix_user_google_oauth2_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_blacklisted_token_jti"), table_name="blacklisted_token")
    op.drop_table("blacklisted_token")
    op.drop_index(op.f("ix_blacklisted_email_sub"), table_name="blacklisted_email")
    op.drop_table("blacklisted_email")
    # ### end Alembic commands ###
