# services for each microservice image to instruct docker on how to build the image and run the container for each service
# service names do not need to match the name of the folder referenced by the service
services:
  redis:
    image: redis:8.2-alpine
    container_name: redis_server_container
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  database:
    image: postgres:17.6-bookworm
    container_name: postgres_database_container
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgres/database
      - pglog:/var/log/postgres

  alembic_migrations:
    image: "${DOCKER_BACKEND_IMAGE}:${DOCKER_BACKEND_IMAGE_TAG?latest}"
    # build command directs docker to the docker file needed to build service image
    build: ./api
    # set the name of the container
    container_name: alembic_migrations_container
    env_file:
      - .env
    environment:
      - DEBUG=False
    command: python -m alembic -c alembic.ini upgrade head
    depends_on:
      - database

  celery_email_worker:
    image: "${DOCKER_BACKEND_IMAGE}:${DOCKER_BACKEND_IMAGE_TAG?latest}"
    build: ./api
    container_name: celery_email_worker_container
    command: python -m celery -A src.background_tasks.celery_email_verification_task.celery_email_verification_app worker
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      - redis

  backend:
    image: ${DOCKER_BACKEND_IMAGE}:${DOCKER_BACKEND_IMAGE_TAG?latest}
    build: ./api
    container_name: api_container
    env_file:
      - .env
    environment:
      - FRONTEND_SERVICE_NAME=frontend
      - FRONTEND_SERVICE_PORT=80
      - DEBUG=False
    ports:
      - "8000:8000"
    command: python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 --reload-dir .
    depends_on:
      - redis
      - database
      - alembic_migrations
      - celery_email_worker

  frontend:
    image: "${DOCKER_FRONTEND_IMAGE}:${DOCKER_FRONTEND_IMAGE_TAG?latest}"
    build: ./frontend
    container_name: frontend_container
    env_file:
      - .env
    environment:
      - VITE_ACCOUNT_SUSPENDED_ERROR_CODE=${ACCOUNT_SUSPENDED_ERROR_CODE}
      - VITE_NOT_ADMIN_ERROR_CODE=${NOT_ADMIN_ERROR_CODE}
      - VITE_DEBUG=False
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: {}
  pglog: {}
  redisdata: {}
