[pytest]
asyncio_mode = auto
env =
    TESTING=1
    DEBUG=0
testpaths = 
    **/tests
python_files = 
    test_*.py
    _test.py
python_functions = 
    test_*
    _test
addopts = 
    -v
    --cov
    --cov-report=html