[pytest]
asyncio_mode = auto
env =
    TESTING=1
testpaths = 
    **/tests
python_files = 
    test_*.py
    _test.py
python_functions = 
    test_*
    _test
addopts = 
    -v
    --cov
    --cov-report=html
markers =
    slow: mark as slow test
    unit: mark as unit test
    api: mark as api test
    integration: mark as integration test

    chat: mark as chat test
    auth: mark as auth test
    user: mark as user auth test